# Generated by Django 3.0.4 on 2020-05-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200518_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=72)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='groups',
            field=models.ManyToManyField(to='reports.CompanyGroup'),
        ),
    ]
