# Generated by Django 3.0.4 on 2020-04-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='services',
            name='num',
            field=models.CharField(max_length=64),
        ),
    ]
