# Generated by Django 3.0.8 on 2020-07-13 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0006_auto_20200424_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSheetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_submitter', models.CharField(max_length=164)),
                ('beginning_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_library.Equipment')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_library.EquipmentSheetGroup')),
            ],
        ),
    ]
