# Generated by Django 3.1.7 on 2021-04-05 21:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0007_equipmentsheet_equipmentsheetgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentsheet',
            name='group',
        ),
        migrations.AddField(
            model_name='equipmentsheet',
            name='beginning_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentsheet',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentsheet',
            name='name_of_submitter',
            field=models.CharField(default=django.utils.timezone.now, max_length=164),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EquipmentSheetGroup',
        ),
    ]
